export const artifactOrder = [
  "REQUIREMENTS.md",
  "USER_STORY.md",
  "ANALYSIS.md",
  "DESIGN.md",
  "ADR.md",
  "TEST_PLAN.md",
  "TEST_CASE_MATRIX.md",
  "RISK_REGISTER.md",
  "QUALITY_ATTRIBUTE_SCENARIOS.md",
  "SECURITY_REVIEW.md",
  "AI_USAGE_REVIEW.md",
  "PROCESS_COMPLIANCE_REPORT.md",
  "DEPLOYMENT_PLAN.md",
  "MAINTENANCE_TASK.md",
  "RETROSPECTIVE.md",
  "FINAL_REPORT.md",
];

export const adoptionFiles = [
  "AGENTS.md",
  "docs/software-engineering/17_REVISION_MASTER_CHECKLIST.md",
  "docs/software-engineering/18_TRACEABILITY_MATRIX.md",
  "templates/REQUIREMENTS_TEMPLATE.md",
  ".agents/skills/software-engineering-governor/SKILL.md",
  "scripts/se_gate.py",
  ".github/pull_request_template.md",
  ".github/workflows/se-quality-gate.yml",
];

const safe = (value, fallback) => String(value || fallback).replace(/[<>]/g, "").trim();
const stamp = () => new Date().toISOString().slice(0, 10);
const valueList = (value, fallback = []) => {
  const source = Array.isArray(value) ? value : typeof value === "string" ? value.split(/\r?\n|;/) : [];
  const cleaned = source.map((item) => safe(item, "")).filter(Boolean);
  return cleaned.length ? cleaned : fallback;
};
const stripTraceId = (value) => safe(value, "").replace(/^(?:FR|NFR|AC|CON|OOS)-\d{3}\s*[:.-]?\s*/i, "");
const markdownCell = (value) => safe(value, "").replaceAll("|", "\\|").replace(/\s+/g, " ");
const bulletList = (values, fallback) => valueList(values, [fallback]).map((item) => `- ${stripTraceId(item)}`).join("\n");

export function createTaskArtifacts(project = {}, task = {}) {
  const name = safe(project.name, "Untitled Project");
  const title = safe(task.title, "Engineering Task");
  const type = safe(task.type, "Feature");
  const goal = safe(task.goal, "Deliver the requested behavior with traceable engineering evidence.");
  const problem = safe(task.problem, task.background || "The current workflow does not satisfy the stated user need.");
  const constraints = safe(task.constraints, "Minimal reversible change; no undocumented behavior change.");
  const acceptance = safe(task.acceptance, "The primary behavior is demonstrably correct and regression evidence passes.");
  const risk = safe(task.risk, "Incorrect assumptions may create behavior or security regressions.");
  const rollback = safe(task.rollback, "Disable or revert the isolated change and restore the previous artifact set.");
  const security = safe(project.security, "Medium");
  const stack = safe(project.stack, "To be confirmed");

  return {
    "REQUIREMENTS.md": `# Requirements: ${title}\n\n## Traceability ID\n- Requirement set ID: ${safe(task.id, "TASK-001")}\n- Project: ${name}\n- Owner: To be assigned\n\n## Stakeholders\n| Stakeholder | Interest | Priority | Source |\n|---|---|---|---|\n| End user | ${goal} | High | Product request |\n| Maintainer | Safe, maintainable delivery | High | Engineering review |\n\n## Problem Statement\n${problem}\n\n## Functional Requirements\n| ID | Requirement | Source | Acceptance Link | Status |\n|---|---|---|---|---|\n| FR-001 | ${goal} | User request | AC-001 | Draft |\n\n## Non-functional Requirements\n| ID | Attribute | Requirement | Measure | Verification |\n|---|---|---|---|---|\n| NFR-001 | Security | Preserve the ${security} security boundary. | Security review has no unaccepted critical finding. | Review |\n| NFR-002 | Maintainability | Keep the change isolated and documented. | Named owner, rollback, and regression evidence exist. | Review |\n\n## Constraints\n- ${constraints}\n- Technology stack: ${stack}\n\n## Assumptions\n- A-001: Stakeholders will review unresolved questions before implementation.\n\n## Requirement Conflicts\n| ID | Conflict | Stakeholders | Resolution | Owner |\n|---|---|---|---|---|\n| RC-001 | Delivery speed versus assurance depth | Product / Engineering | Risk-based review depth | Product owner |\n\n## Acceptance Criteria\n- AC-001: ${acceptance}\n`,
    "USER_STORY.md": `# User Story: ${title}\n\n## Epic\n- Epic ID: ${safe(task.epic, "GOVERNED-DELIVERY")}\n- Epic goal: ${goal}\n\n## Story\nAs a project stakeholder, I want ${goal.toLowerCase()}, so that the project delivers measurable value without losing engineering evidence.\n\n## Role\nProject stakeholder\n\n## Goal\n${goal}\n\n## Benefit\nA reviewable and reversible ${type.toLowerCase()} outcome.\n\n## Priority\n- Business value: High\n- Risk reduction: High\n- Dependency: Stakeholder acceptance\n\n## MoSCoW\n- Must\n\n## Story Points\n- Fibonacci estimate: 5\n- Uncertainty: Requirements and integration context\n\n## INVEST Checklist\n- [x] Independent\n- [x] Negotiable\n- [x] Valuable\n- [x] Estimable\n- [x] Small\n- [x] Testable\n\n## Acceptance Criteria\n- AC-001: ${acceptance}\n- AC-002: Invalid and boundary inputs fail safely.\n- AC-003: Existing behavior remains covered by regression evidence.\n\n## Tasks\n| Task ID | Task | Owner | Status |\n|---|---|---|---|\n| T-001 | Confirm requirements and acceptance evidence | Maintainer | Planned |\n| T-002 | Implement the smallest reversible change | Maintainer | Planned |\n| T-003 | Run tests, security review, and documentation update | Reviewer | Planned |\n`,
    "ANALYSIS.md": `# Analysis: ${title}\n\n## Domain Concepts\n| Concept | Meaning | Business Rule |\n|---|---|---|\n| Project | Governed software context | Owns task evidence |\n| Task package | Traceable lifecycle evidence | Must link requirements to tests |\n\n## Entities\n| Entity | Responsibility | Persistent Data | Invariants |\n|---|---|---|---|\n| Task | Coordinates ${type} work | IDs, status, evidence | Requirement IDs remain stable |\n\n## Boundary Objects\n| Boundary | External Actor/System | Input | Output |\n|---|---|---|---|\n| User interface | Stakeholder | Task context | Validated artifacts |\n\n## Control Objects\n| Control | Workflow | Coordinates | Failure Handling |\n|---|---|---|---|\n| TaskController | Evidence lifecycle | Requirements, tests, reviews | Preserves drafts and reports gaps |\n\n## Relationships\n| Source | Relationship | Target | Reason |\n|---|---|---|---|\n| Requirement | Verified by | Test case | Traceability |\n\n## Multiplicity\n| Relationship | Multiplicity | Constraint |\n|---|---|---|\n| Task to requirement | 1 to 1..* | Every task has an observable requirement |\n\n## Data Flow\n1. Capture context and constraints.\n2. Validate required evidence.\n3. Produce linked artifacts.\n4. Review failures and residual risk.\n5. Export a reversible package.\n\n## Failure Modes\n| Failure | Cause | Detection | Handling | Test Link |\n|---|---|---|---|---|\n| Missing trace | Incomplete artifact | Static validation | Mark FAIL and generate repair prompt | TC-003 |\n| Unsafe input | Malformed archive or content | Boundary checks | Reject without execution | TC-004 |\n`,
    "DESIGN.md": `# Design Document: ${title}\n\n## Design Goal\n${goal}\n\n## Current Architecture\nProject-specific architecture requires repository review before implementation.\n\n## Proposed Architecture\nAdd the smallest bounded component or change that satisfies FR-001.\n\n## Alternatives Considered\n| Alternative | Pros | Cons | Decision |\n|---|---|---|---|\n| Local bounded change | Reversible and testable | May defer broad cleanup | Selected |\n| Broad rewrite | Uniform result | High regression risk | Rejected |\n\n## Module Boundaries\n| Module | Responsibility | Owns | Does Not Own |\n|---|---|---|---|\n| Task boundary | ${goal} | Task policy | Unrelated project behavior |\n\n## Interfaces\n| Interface | Consumer | Provider | Contract | Error Behavior |\n|---|---|---|---|---|\n| Task operation | Existing workflow | New bounded component | FR-001 / AC-001 | Explicit safe failure |\n\n## Data Model\nNo data model change without an explicit migration decision.\n\n## SOLID Review\n- SRP: Keep task policy separate from unrelated behavior.\n- OCP: Add extension points only for demonstrated variation.\n- LSP: Preserve existing consumer expectations.\n- ISP: Expose only required operations.\n- DIP: Isolate volatile infrastructure behind a narrow boundary when justified.\n\n## Pattern Justification\n| Pattern | Design Pressure | Simpler Alternative | Consequences |\n|---|---|---|---|\n| None initially | No proven recurring pressure | Direct bounded module | Avoids premature abstraction |\n\n## Quality Attribute Impact\n| Attribute | Positive Impact | Negative Impact | Evidence |\n|---|---|---|---|\n| Maintainability | Local responsibility | Additional module | Review and regression tests |\n| Security | Explicit boundary | Review cost | Security review |\n`,
    "ADR.md": `# Architecture Decision Record: ${title}\n\n## Status\nProposed\n\n## Context\n${problem}\n\n## Decision\nUse a minimal, reversible boundary for ${goal.toLowerCase()}.\n\n## Alternatives\n| Alternative | Why Considered | Why Rejected/Accepted |\n|---|---|---|\n| Local change | Lowest blast radius | Accepted |\n| Broad rewrite | Potential uniformity | Rejected: unjustified risk |\n\n## Consequences\n- Positive: Clear ownership and rollback.\n- Negative: Some existing debt may remain.\n- Neutral: Existing interfaces remain authoritative.\n\n## Quality Attributes Affected\n| Attribute | Effect | Response Measure |\n|---|---|---|\n| Reliability | Lower regression surface | Required tests pass |\n| Maintainability | Clearer boundary | Review finds no mixed responsibility |\n\n## Risk\n| Risk | Probability | Impact | Mitigation |\n|---|---|---|---|\n| ${risk} | Medium | High | Tests, review, staged release |\n\n## Rollback\n${rollback}\n`,
    "TEST_PLAN.md": `# Test Plan: ${title}\n\n## Scope\nFR-001, NFR-001, NFR-002, and AC-001 through AC-003.\n\n## Test Levels\n- Unit: Policy and validation behavior.\n- Integration: Boundary contracts.\n- System: End-to-end user outcome.\n- Acceptance: Stakeholder-observable behavior.\n\n## Test Strategy\n- Black-box: Normal, boundary, invalid, and security inputs.\n- White-box: Branches and failure handling.\n- Regression: Existing behavior around affected modules.\n- Security: Trust-boundary and unsafe-input cases.\n\n## Tools\nUse the project's existing test tools; do not add a dependency without review.\n\n## Test Data\nSynthetic normal, boundary, malformed, and adversarial data only.\n\n## Traceability\n| Requirement ID | Acceptance Criteria | Test ID |\n|---|---|---|\n| FR-001 | AC-001 | TC-001, TC-002 |\n| NFR-001 | AC-002 | TC-004 |\n| NFR-002 | AC-003 | TC-005 |\n\n## Pass/Fail Criteria\nAll critical and regression tests pass; no unaccepted security finding remains.\n\n## Regression Plan\nRun the affected suite before merge and again before release.\n`,
    "TEST_CASE_MATRIX.md": `# Test Case Matrix: ${title}\n\n| Test ID | Requirement ID | Test Type | Input | Expected Output | Reason | Coverage | Status |\n|---|---|---|---|---|---|---|---|---|\n| TC-001 | FR-001 / AC-001 | Normal | Valid task input | ${acceptance} | Main behavior | Acceptance | Planned |\n| TC-002 | FR-001 / AC-001 | Boundary | Minimum supported input | Stable bounded result | Boundary behavior | Boundary | Planned |\n| TC-003 | FR-001 / AC-002 | Invalid | Missing or malformed input | Clear safe error | Failure handling | Negative path | Planned |\n| TC-004 | NFR-001 / AC-002 | Security | Adversarial input | Rejected without unsafe execution | Trust boundary | Security | Planned |\n| TC-005 | NFR-002 / AC-003 | Regression | Existing supported flow | Behavior preserved | Prevent regression | Regression | Planned |\n`,
    "RISK_REGISTER.md": `# Risk Register: ${title}\n\n| Risk ID | Description | Category | Probability | Impact | Exposure | Mitigation | Contingency | Residual risk | Trigger | Detection method | Review cadence | Owner | Status |\n|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| R-001 | ${risk} | Technical | Medium | High | High | Requirements, tests, staged review | ${rollback} | Medium | Validation failure | Test and review evidence | PR and release | Maintainer | Open |\n| R-002 | Unsafe input crosses a trust boundary | Security | Low | High | Medium | Validate and never execute uploads | Reject input | Low | Malformed archive | Static archive inspection | Every upload | Security owner | Open |\n`,
    "QUALITY_ATTRIBUTE_SCENARIOS.md": `# Quality Attribute Scenarios: ${title}\n\n| Scenario ID | Attribute | Stimulus | Environment | Response | Response Measure | Architecture View | Test Evidence | Risk | Trade-off |\n|---|---|---|---|---|---|---|---|---|---|\n| QS-001 | Security | Untrusted input reaches the task boundary | Normal operation | Reject unsafe input without exposing internals | No unaccepted high-severity finding | Process / logical | TC-004 | R-002 | Additional validation cost |\n| QS-002 | Reliability | A task operation fails part-way | Degraded dependency | Preserve consistent state and expose a retry path | Recovery and rollback test passes | Process | TC-003, TC-005 | R-001 | More explicit state handling |\n| QS-003 | Performance | A critical user path runs under representative load | Staging-like environment | Stay within the owner-confirmed baseline or explain variance | Comparable baseline report exists | Deployment | Project-specific | R-001 | Measurement effort |\n`,
    "SECURITY_REVIEW.md": `# Security Review: ${title}\n\n## Threat Model\nUntrusted input may attempt traversal, injection, secret exposure, or unintended execution.\n\n## Trust Boundaries\nUser input, repository files, CI, deployment configuration, and external services.\n\n## Input Validation\nValidate type, size, count, path, encoding, and required fields before processing.\n\n## Authentication\nNo authentication change unless separately approved.\n\n## Authorization\nEnforce authorization server-side for protected operations.\n\n## Secrets\nNo credentials in source, artifacts, logs, or generated prompts.\n\n## Error Handling\nReturn bounded errors without sensitive internals.\n\n## Logging\nLog status metadata only; never log uploaded content or secrets.\n\n## Dependency Risk\nReview any new dependency, license, integrity, and maintenance status.\n\n## AI-generated Code Risk\nTreat generated output as untrusted until human review and tests complete.\n\n## Deployment Risk\nUse staged release, monitoring, and explicit rollback criteria.\n\n## Security Test Plan\nTC-004 covers adversarial input; project-specific auth and injection cases remain required.\n\n## Residual Risk\n${risk}\n`,
    "AI_USAGE_REVIEW.md": `# AI Usage Review: ${title}\n\n## AI Tool Used\nCodex or project-approved assistant\n\n## Task Scope\nDrafting lifecycle evidence for ${type}: ${title}.\n\n## AI-generated Code Yes/No\nNo code generated by this artifact package.\n\n## Generated Code Reviewed By Human\n- Reviewer: Required before implementation\n- Evidence: PR review and test results\n\n## Human Review Yes/No\nPending\n\n## Security-sensitive Areas\n${security} security boundary and uploaded content.\n\n## Privacy-sensitive Areas\nProject files, user identifiers, logs, and secrets.\n\n## IP/License Risk\nReview generated or copied material before distribution.\n\n## Bias/Fairness Risk\nReview if the task affects consequential user decisions.\n\n## Hallucination Risk\nVerify APIs, requirements, and project structure against authoritative source.\n\n## Tests Added\nTC-001 through TC-005 planned.\n\n## Final Human Decision\nRequest changes until implementation evidence exists.\n`,
    "PROCESS_COMPLIANCE_REPORT.md": `# Process Compliance Report: ${title}\n\n## Traceability\n- Report ID: PCR-${stamp()}\n- Task or PR: ${title}\n- Owner: To be assigned\n- Date: ${stamp()}\n\n## Selected Process Model\n- Selected process model: ${safe(project.process, "Agile")}\n- Alternatives considered: Waterfall, Spiral, V Model\n- Why this model fits requirement stability and risk: Short feedback and reversible increments suit current uncertainty.\n\n## Agile Iteration Evidence\n- Iteration or increment: One bounded task package\n- Working software evidence: Required before completion\n- Feedback received: Pending stakeholder review\n- Change incorporated: Pending\n\n## Required Documentation Level\n- Required documentation: Full task package for ${security} risk\n- Reason documentation level is sufficient: Covers lifecycle and rollback evidence\n- Deferred documentation: Product-specific operations details\n\n## Test Timing\n- Tests before implementation: Acceptance and regression cases defined\n- Tests during implementation: Unit and integration tests\n- Tests before release: System, security, and regression tests\n\n## Stakeholder Feedback Loop\n- Stakeholders consulted: Product owner, maintainer, security reviewer\n- Feedback cadence: Every reviewable increment\n- Open feedback: Confirm AC-001\n\n## Release Cadence\n- Planned release cadence: Small staged release\n- Release readiness criteria: Tests and reviews pass\n- Rollback condition: Critical regression or security finding\n\n## Retrospective Evidence\n- What changed: Pending\n- What worked: Pending\n- What failed: Pending\n- Rule or memory update suggestion: Pending after validation\n`,
    "DEPLOYMENT_PLAN.md": `# Deployment Plan: ${title}\n\n## Deployment Scope\n- Feature or change: ${goal}\n- Environment: Staging then production\n- Affected users: Project stakeholders\n\n## Preconditions\n- Build artifact: Reproducible versioned artifact\n- Configuration: Reviewed and secret-free\n- Dependencies: Healthy and approved\n- Data migration: None unless separately documented\n\n## Release Steps\n| Step | Command or Action | Owner | Verification |\n|---|---|---|---|\n| DEP-001 | Deploy to staging | Release owner | Acceptance and security evidence |\n| DEP-002 | Promote gradually | Release owner | Monitoring remains within thresholds |\n\n## Monitoring\n- Metrics: Error rate, latency, user outcome\n- Logs: Redacted structured events\n- Alert: Regression or security threshold\n- Review window: First 24 hours\n\n## Rollback Criteria\n- Trigger: Critical failure, data risk, or security regression\n- Threshold: Any uncontained critical impact\n- Decision owner: Release owner\n\n## Rollback Steps\n| Step | Command or Action | Owner | Verification |\n|---|---|---|---|\n| RB-001 | ${rollback} | Release owner | Previous behavior restored |\n\n## Known Risks\n- Risk ID: R-001, R-002\n- Mitigation: Staged rollout and monitoring\n- Residual risk: Project-specific runtime behavior\n\n## Post-release Review\n- Evidence: Metrics snapshot and stakeholder feedback\n- Follow-up: Update retrospective and maintenance task\n`,
    "MAINTENANCE_TASK.md": `# Maintenance Task: ${title}\n\n## Maintenance Goal\n- Goal: Preserve correctness, security, and traceability after release.\n- Trigger: Regression, dependency change, monitoring signal, or retrospective.\n- Related requirement: FR-001, NFR-001, NFR-002\n\n## System Area\n- Module: Affected task boundary\n- Owner: Maintainer\n- Operational context: ${safe(project.stage, "Development")}\n\n## Maintenance Type\n- Corrective: Fix verified defects.\n- Adaptive: Respond to platform changes.\n- Perfective: Improve maintainability with behavior-preserving tests.\n- Preventive: Review risks and dependencies.\n\n## Impact Analysis\n- Users affected: Project stakeholders\n- Data affected: Confirm before change\n- Interfaces affected: Confirm before change\n- Documentation affected: Task package and release notes\n\n## Test And Regression Plan\n- Regression tests: TC-001 through TC-005\n- Failure-path tests: TC-003 and TC-004\n- Monitoring evidence: Release metrics\n\n## Risk And Residual Risk\n- Risk ID: R-001, R-002\n- Mitigation: Tests, review, staged release\n- Residual risk: ${risk}\n\n## Release Or Scheduling Window\n- Target date or cadence: Each release and quarterly review\n- Dependency: Owner availability\n- Communication: Release notes\n\n## Completion Evidence\n- Commands run: Record actual commands\n- Documentation updated: Record actual files\n- Retrospective note: Capture reusable lessons\n`,
    "RETROSPECTIVE.md": `# Retrospective: ${title}\n\n## What Changed\nPending implementation and release evidence.\n\n## What Worked\nRecord practices supported by actual run evidence.\n\n## What Failed\nRecord failed checks, rejected assumptions, or delivery friction.\n\n## Root Cause\nLink each repeated or material failure to a verified cause, not a symptom.\n\n## Engineering Rule To Update\nPropose a rule only when the evidence is reusable beyond this task.\n\n## Memory Update Suggestion\nPending review after the release decision.\n\n## Future Prevention\n| Action | Owner | Target | Verification |\n|---|---|---|---|\n| Review unresolved evidence | Maintainer | Next iteration | Required check passes |\n`,
    "FINAL_REPORT.md": `# Final Engineering Report: ${title}\n\n## Requirements Satisfied\nPending implementation evidence for FR-001, NFR-001, and NFR-002.\n\n## Analysis Summary\nDomain, boundaries, relationships, and failure modes are recorded in ANALYSIS.md.\n\n## Design Decisions\nUse a minimal reversible boundary; no pattern without demonstrated pressure.\n\n## Files Changed\nPending implementation.\n\n## Tests Added / Updated\nTC-001 through TC-005 are planned; replace with actual evidence.\n\n## Commands Run\nPending implementation.\n\n## Security Review\nThreat model and trust boundaries recorded; final human review remains required.\n\n## Quality Review\nMaintainability, reliability, and security evidence required before approval.\n\n## Documentation Updated\nThis task package generated ${stamp()}.\n\n## Risks Remaining\nR-001 and R-002 remain open until implementation validation.\n\n## Rollback Plan\n${rollback}\n\n## Memory Update Suggestions\nPropose only after a verified reusable lesson is observed.\n`,
  };
}

export function createTraceableTaskArtifacts(project = {}, task = {}) {
  const base = createTaskArtifacts(project, task);
  const name = safe(project.name, "Untitled Project");
  const title = safe(task.title, "Engineering Task");
  const type = safe(task.type, "Feature");
  const goal = safe(task.goal, "Confirm the target outcome before implementation.");
  const problem = safe(task.problem, task.background || "Confirm the user problem before implementation.");
  const security = safe(project.security, "Medium");
  const stack = safe(project.stack, "To be confirmed");
  const stakeholders = valueList(task.stakeholders, ["End user", "Product owner", "Maintainer"]);
  const functional = valueList(task.functional, [goal]);
  const scenarios = Array.isArray(task.qualityScenarios) ? task.qualityScenarios.filter((item) => item && typeof item === "object") : [];
  const nonFunctional = valueList(task.nonFunctional, scenarios.map((item) => `${safe(item.attribute, "Quality")}: ${safe(item.expectedResponse, "Confirm a measurable response.")}`));
  if (!nonFunctional.length) nonFunctional.push(`Security: Preserve the ${security} security boundary.`, "Maintainability: Keep the change isolated, reviewable, and reversible.");
  const acceptanceDetails = Array.isArray(task.acceptanceDetails) && task.acceptanceDetails.length
    ? task.acceptanceDetails
    : [{ id: "AC-001", kind: "normal", context: "the supported workflow is available", action: "the user completes the requested action", expected: safe(task.acceptance, "the confirmed outcome is observed") }];
  const assumptions = valueList(task.assumptions, ["Stakeholders will resolve open questions before implementation."]);
  const conflicts = valueList(task.conflicts, ["Delivery speed versus assurance depth"]);
  const securityRequirements = valueList(task.securityRequirements, ["Validate trust boundaries and reject unsafe input."]);
  const outOfScope = valueList(task.outOfScope, ["Unrelated modules and behavior not named by this task."]);
  const story = task.userStory && typeof task.userStory === "object" ? task.userStory : {};
  const functionalRows = functional.map((item, index) => `| FR-${String(index + 1).padStart(3, "0")} | ${markdownCell(stripTraceId(item))} | User-confirmed requirement | AC-${String(Math.min(index + 1, acceptanceDetails.length)).padStart(3, "0")} | Confirmed |`).join("\n");
  const nonFunctionalRows = nonFunctional.map((item, index) => {
    const scenario = scenarios[index];
    const verification = safe(scenario?.verification, "Owner-approved review and test evidence");
    return `| NFR-${String(index + 1).padStart(3, "0")} | ${markdownCell(scenario?.attribute || "Quality")} | ${markdownCell(stripTraceId(item))} | ${markdownCell(verification)} | ${markdownCell(verification)} |`;
  }).join("\n");
  const acceptanceRows = acceptanceDetails.map((item, index) => {
    const id = safe(item.id, `AC-${String(index + 1).padStart(3, "0")}`);
    return `- ${id} (${safe(item.kind, "normal")}): Given ${safe(item.context, "a confirmed precondition")}, when ${safe(item.action, "the action occurs")}, then ${safe(item.expected, "the expected result is observable")}.`;
  }).join("\n");
  const testRows = acceptanceDetails.map((item, index) => {
    const acId = safe(item.id, `AC-${String(index + 1).padStart(3, "0")}`);
    const frId = `FR-${String(Math.min(index + 1, functional.length)).padStart(3, "0")}`;
    return `| TC-${String(index + 1).padStart(3, "0")} | ${frId} / ${acId} | ${markdownCell(item.kind || "Normal")} | Given ${markdownCell(item.context || "confirmed context")}; when ${markdownCell(item.action || "the action occurs")} | ${markdownCell(item.expected || "confirmed result") } | Proves ${acId} | ${markdownCell(item.kind || "behavior")} | Planned |`;
  });
  scenarios.forEach((scenario, index) => {
    const testIndex = acceptanceDetails.length + index + 1;
    testRows.push(`| TC-${String(testIndex).padStart(3, "0")} | NFR-${String(index + 1).padStart(3, "0")} | ${markdownCell(scenario.attribute || "Quality")} | ${markdownCell(scenario.condition || "quality stimulus occurs")} | ${markdownCell(scenario.expectedResponse || "required response is observed")} | Proves ${markdownCell(scenario.id || `QS-${index + 1}`)} | ${markdownCell(scenario.verification || "quality evidence")} | Planned |`);
  });
  const qualityRows = scenarios.length
    ? scenarios.map((scenario, index) => `| ${markdownCell(scenario.id || `QS-${String(index + 1).padStart(3, "0")}`)} | ${markdownCell(scenario.attribute || "Quality")} | ${markdownCell(scenario.condition || "Stimulus occurs")} | Project operating environment | ${markdownCell(scenario.expectedResponse || "Required response")} | ${markdownCell(scenario.verification || "Owner-confirmed evidence")} | ${scenario.attribute === "performance" ? "Deployment" : "Logical / process"} | TC-${String(acceptanceDetails.length + index + 1).padStart(3, "0")} | R-${String(index + 1).padStart(3, "0")} | Assurance effort |`).join("\n")
    : "| QS-001 | Security | Untrusted input reaches the task boundary | Normal operation | Reject unsafe input without exposing internals | Security review and adversarial test pass | Process / logical | TC-001 | R-001 | Validation effort |";

  base["REQUIREMENTS.md"] = `# Requirements: ${title}\n\n## Traceability ID\n- Requirement set ID: ${safe(task.id, "TASK-001")}\n- Project: ${name}\n- Owner: To be assigned\n\n## Stakeholders\n| Stakeholder | Interest | Priority | Source |\n|---|---|---|---|\n${stakeholders.map((item) => `| ${markdownCell(item)} | ${markdownCell(goal)} | High | User-confirmed context |`).join("\n")}\n\n## Problem Statement\n${problem}\n\n## Functional Requirements\n| ID | Requirement | Source | Acceptance Link | Status |\n|---|---|---|---|---|\n${functionalRows}\n\n## Non-functional Requirements\n| ID | Attribute | Requirement | Measure | Verification |\n|---|---|---|---|---|\n${nonFunctionalRows}\n\n## Constraints\n${bulletList(task.constraints, "Minimal reversible change; no undocumented behavior change.")}\n- Technology stack: ${stack}\n\n## Assumptions\n${assumptions.map((item, index) => `- A-${String(index + 1).padStart(3, "0")}: ${stripTraceId(item)}`).join("\n")}\n\n## Requirement Conflicts\n| ID | Conflict | Stakeholders | Resolution | Owner |\n|---|---|---|---|---|\n${conflicts.map((item, index) => `| RC-${String(index + 1).padStart(3, "0")} | ${markdownCell(item)} | Product / Engineering | Resolve before implementation | Product owner |`).join("\n")}\n\n## Security Requirements\n${bulletList(securityRequirements, `Preserve the ${security} security boundary.`)}\n\n## Out Of Scope\n${bulletList(outOfScope, "Unrelated behavior")}\n\n## Acceptance Criteria\n${acceptanceRows}\n`;
  base["USER_STORY.md"] = `# User Story: ${title}\n\n## Epic\n- Epic ID: ${safe(task.epic, "GOVERNED-DELIVERY")}\n- Epic goal: ${goal}\n\n## Story\nAs a ${safe(story.role, "project stakeholder")}, I want ${safe(story.goal, goal).toLowerCase()}, so that ${safe(story.benefit, `the ${type.toLowerCase()} outcome is useful, reviewable, and reversible`)}.\n\n## Role\n${safe(story.role, "Project stakeholder")}\n\n## Goal\n${safe(story.goal, goal)}\n\n## Benefit\n${safe(story.benefit, `A reviewable and reversible ${type.toLowerCase()} outcome.`)}\n\n## Priority\n- Business value: High\n- Risk reduction: High\n- Dependency: Stakeholder acceptance\n\n## MoSCoW\n- Must\n\n## Story Points\n- Fibonacci estimate: 5\n- Uncertainty: Requirements and integration context\n\n## INVEST Checklist\n- [x] Independent\n- [x] Negotiable\n- [x] Valuable\n- [x] Estimable\n- [x] Small\n- [x] Testable\n\n## Acceptance Criteria\n${acceptanceRows}\n\n## Tasks\n| Task ID | Task | Owner | Status |\n|---|---|---|---|\n| T-001 | Confirm requirements and acceptance evidence | Maintainer | Planned |\n| T-002 | Implement the smallest reversible change | Maintainer | Planned |\n| T-003 | Run tests, security review, and documentation update | Reviewer | Planned |\n`;
  base["TEST_PLAN.md"] = `# Test Plan: ${title}\n\n## Scope\n${functional.map((_, index) => `FR-${String(index + 1).padStart(3, "0")}`).join(", ")}; ${nonFunctional.map((_, index) => `NFR-${String(index + 1).padStart(3, "0")}`).join(", ")}; ${acceptanceDetails.map((item, index) => safe(item.id, `AC-${String(index + 1).padStart(3, "0")}`)).join(", ")}.\n\n## Test Levels\n- Unit: Decision logic and isolated behavior.\n- Integration: Module and trust-boundary contracts.\n- System: End-to-end user outcome.\n- Acceptance: Stakeholder-observable behavior.\n\n## Test Strategy\n- Black-box: Confirm every acceptance scenario using observable input and output.\n- White-box: Cover decision branches, errors, and cleanup paths.\n- Regression: Preserve behavior named in the confirmed scope.\n- Security: Exercise the confirmed security requirements and trust boundaries.\n\n## Tools\nUse the project's existing test tools; do not add a dependency without review.\n\n## Test Data\nUse synthetic normal, boundary, malformed, and adversarial data. Do not copy production secrets or personal data.\n\n## Traceability\n| Requirement ID | Acceptance Criteria | Test ID |\n|---|---|---|\n${acceptanceDetails.map((item, index) => `| FR-${String(Math.min(index + 1, functional.length)).padStart(3, "0")} | ${safe(item.id, `AC-${String(index + 1).padStart(3, "0")}`)} | TC-${String(index + 1).padStart(3, "0")} |`).join("\n")}\n${scenarios.map((_, index) => `| NFR-${String(index + 1).padStart(3, "0")} | Quality scenario | TC-${String(acceptanceDetails.length + index + 1).padStart(3, "0")} |`).join("\n")}\n\n## Pass/Fail Criteria\nAll required tests pass; no mandatory check is not-run or unknown; no unaccepted security finding remains.\n\n## Regression Plan\nRun affected tests before merge and repeat the release suite against the exact candidate revision.\n`;
  base["TEST_CASE_MATRIX.md"] = `# Test Case Matrix: ${title}\n\n| Test ID | Requirement ID | Test Type | Input | Expected Output | Reason | Coverage | Status |\n|---|---|---|---|---|---|---|---|---|\n${testRows.join("\n")}\n`;
  base["QUALITY_ATTRIBUTE_SCENARIOS.md"] = `# Quality Attribute Scenarios: ${title}\n\n| Scenario ID | Attribute | Stimulus | Environment | Response | Response Measure | Architecture View | Test Evidence | Risk | Trade-off |\n|---|---|---|---|---|---|---|---|---|---|\n${qualityRows}\n`;
  base["SECURITY_REVIEW.md"] = `# Security Review: ${title}\n\n## Confirmed Security Requirements\n${bulletList(securityRequirements, `Preserve the ${security} security boundary.`)}\n\n## Threat Model\nUntrusted input may attempt traversal, injection, secret exposure, authorization bypass, or unintended execution.\n\n## Trust Boundaries\nUser input, repository files, AI provider calls, local runner, CI, deployment configuration, and external services.\n\n## Input Validation\nValidate type, size, count, path, encoding, and required fields before processing.\n\n## Authentication\nUse server-side credential verification where the confirmed scope includes accounts.\n\n## Authorization\nEnforce authorization server-side for each protected resource and test denial paths.\n\n## Secrets\nNo credentials in source, browser storage, artifacts, logs, or generated prompts.\n\n## Error Handling\nReturn bounded errors without stack traces, credentials, or sensitive internal state.\n\n## Logging\nRecord decision metadata and correlation IDs; exclude uploaded content and secrets.\n\n## Dependency Risk\nReview any new dependency, license, integrity, and maintenance status.\n\n## AI-generated Code Risk\nTreat generated output as untrusted until human review and linked tests complete.\n\n## Deployment Risk\nUse ${safe(project.release, "staged")} release, monitoring, and explicit rollback criteria.\n\n## Security Test Plan\nSecurity acceptance scenarios and NFR-linked tests in TEST_CASE_MATRIX.md must pass.\n\n## Residual Risk\n${safe(task.risk, "Confirm residual risk after implementation.")}\n`;
  base["DEPLOYMENT_PLAN.md"] = base["DEPLOYMENT_PLAN.md"].replace("- Environment: Staging then production", `- Environment: ${safe(project.environment, "Staging then production")}\n- Release strategy: ${safe(project.release, "Staged")}`);
  return base;
}

export function projectContextArtifact(project = {}) {
  return `# Project Context: ${safe(project.name, "Untitled Project")}\n\n## Software Type Classification\n- Primary type: ${safe(project.softwareType, "Web application")}\n- Environment: ${safe(project.environment, "Web")}\n- Technology stack: ${safe(project.stack, "To be confirmed")}\n- Project stage: ${safe(project.stage, "Planning")}\n- Team size: ${safe(project.teamSize, "1-5")}\n\n## Data Handled\n- Security level: ${safe(project.security, "Medium")}\n- Privacy level: ${safe(project.privacy, "Medium")}\n- Compliance: ${safe(project.compliance, "None specified")}\n\n## Documentation Required\nRequirements, design, tests, security, deployment, maintenance, and final report.\n\n## User-facing Quality Attributes\n- Performance: ${safe(project.performance, "Measurable response targets required")}\n- Reliability: ${safe(project.reliability, "Failure behavior and rollback required")}\n- Security: ${safe(project.security, "Medium")}\n\n## Developer-facing Quality Attributes\nMaintainability, testability, portability, and traceability.\n\n## Engineering Consequences\n- Required process model: ${safe(project.process, "Agile")}\n- Release method: ${safe(project.release, "Staged")}\n- AI-assisted development: ${project.aiAssisted ? "Yes, with human review" : "No"}\n`;
}

export function traceableProjectContextArtifact(project = {}) {
  const base = projectContextArtifact(project);
  return `${base}\n## Controls Derived From Project Choices\n${bulletList(project.qualityControls, "Confirm controls with the project owner.")}\n\n## Release-blocking Conditions\n${bulletList(project.releaseBlocks, "A mandatory check fails or required evidence is missing.")}\n\n## Required Checks\n${bulletList(project.requiredChecks, "Policy and test checks")}\n\n## Required Artifacts\n${bulletList(project.requiredArtifacts, "Requirements, design, tests, risk, security, and release evidence")}\n`;
}

export function evaluateArtifacts(artifacts = {}) {
  const names = Object.keys(artifacts);
  const missing = artifactOrder.filter((name) => !names.includes(name));
  const text = Object.values(artifacts).join("\n");
  const count = (pattern) => new Set(text.match(pattern) || []).size;
  const requirements = count(/\b(?:FR|NFR)-\d{3}\b/g);
  const acceptance = count(/\bAC-\d{3}\b/g);
  const tests = count(/\bTC-\d{3}\b/g);
  const risks = count(/\bR-\d{3}\b/g);
  const testMatrix = artifacts["TEST_CASE_MATRIX.md"] || "";
  const requirementIds = [...new Set(text.match(/\b(?:FR|NFR)-\d{3}\b/g) || [])];
  const linked = requirementIds.filter((id) => testMatrix.includes(id)).length;
  const statuses = artifactOrder.map((name) => {
    const content = artifacts[name];
    if (!content) return { name, status: "fail", source: "browser-static", detail: "Missing artifact" };
    const incomplete = /\b(?:TODO|TBD|fix later)\b/i.test(content);
    return { name, status: incomplete ? "warning" : "pass", source: "browser-static", detail: incomplete ? "Unresolved placeholder" : "Required artifact present" };
  });
  return {
    artifactCompletion: Math.round(((artifactOrder.length - missing.length) / artifactOrder.length) * 100),
    requirements,
    acceptance,
    tests,
    risks,
    traceability: requirementIds.length ? Math.round((linked / requirementIds.length) * 100) : 0,
    security: artifacts["SECURITY_REVIEW.md"] ? "pass" : "fail",
    aiEvidence: artifacts["AI_USAGE_REVIEW.md"] ? "pass" : "unknown",
    releaseReadiness: missing.length === 0 && linked > 0 ? "warning" : "fail",
    missing,
    statuses,
  };
}

export function checkRepositoryPaths(paths = []) {
  const normalized = paths.map((path) => path.replaceAll("\\", "/").replace(/^\.\//, "").replace(/^\/+/, ""));
  const missing = adoptionFiles.filter((required) => !normalized.some((path) => path === required || path.endsWith(`/${required}`)));
  return {
    score: Math.round(((adoptionFiles.length - missing.length) / adoptionFiles.length) * 100),
    missing,
    passed: adoptionFiles.filter((required) => !missing.includes(required)),
  };
}

export function buildCodexPrompt(project = {}, task = {}, options = {}) {
  const rules = [
    options.plan !== false && "Produce an Engineering Plan before editing.",
    options.tests !== false && "Run relevant tests and report exact commands and results.",
    options.docs !== false && "Update affected documentation.",
    options.finalReport !== false && "Return a Final Engineering Report.",
    options.minimal !== false && "Use the smallest reversible implementation.",
    !options.dependencies && "Do not add dependencies without explicit approval.",
    !options.architecture && "Do not change architecture unless required by an accepted ADR.",
  ].filter(Boolean);
  return `Use the software-engineering-governor skill.\n\nProject: ${safe(project.name, "Untitled Project")}\nTask type: ${safe(task.type, "Feature")}\nTask: ${safe(task.title, "Engineering Task")}\nGoal: ${safe(task.goal, "Confirm the goal before implementation.")}\nProblem: ${safe(task.problem, "Confirm the problem before implementation.")}\nConstraints: ${safe(task.constraints, "Minimal reversible change.")}\nAcceptance: ${safe(task.acceptance, "All accepted criteria and regression evidence pass.")}\nRisk: ${safe(task.risk, "Review security, privacy, and rollback risk.")}\nRollback: ${safe(task.rollback, "Restore the prior behavior and artifacts.")}\n\nMandatory rules:\n${rules.map((rule, index) => `${index + 1}. ${rule}`).join("\n")}\n\nDo not treat AI output as trusted code. Do not execute uploaded or unreviewed scripts. Preserve requirement-to-test traceability and distinguish PASS, FAIL, WARNING, NOT RUN, and UNKNOWN evidence.\n`;
}
