import { ArrowRight, History } from "lucide-react";
import type { WorkflowRun } from "../../domain/model";
import { EmptyState } from "../ui/EmptyState";
import { PageHeader } from "../ui/PageHeader";
import { SourceBadge, StatusBadge } from "../ui/StatusBadge";
import type { WorkspacePageProps } from "../workspace-types";
import { text } from "../workspace-types";

export function HistoryPage({ language, workspace, project, navigate, onSelectRun }: WorkspacePageProps & { onSelectRun: (run: WorkflowRun) => void }) {
  const runs = workspace.runs.filter((item) => item.projectId === project?.id).sort((a, b) => b.startedAt.localeCompare(a.startedAt));
  if (!project) return <EmptyState icon={History} title={text(language, "先选择一个项目", "Select a project first")} description={text(language, "运行历史不会跨项目混合。", "Run history is never mixed across projects.")} actions={<button className="primary-button" onClick={() => navigate("projects")}>{text(language, "查看项目", "View projects")}</button>} />;
  return <div><PageHeader eyebrow={project.name} title={text(language, "运行历史", "Run history")} />{runs.length ? <section className="workspace-panel history-table"><div className="data-table"><div className="table-head history-columns"><span>Run</span><span>Commit</span><span>{text(language, "开始时间", "Started")}</span><span>{text(language, "耗时", "Duration")}</span><span>{text(language, "来源", "Source")}</span><span>{text(language, "结果", "Result")}</span><span /></div>{runs.map((run) => <button className="table-row history-columns" key={run.id} onClick={() => { onSelectRun(run); navigate("run"); }}><span className="table-primary"><b>Run #{run.sequence}</b><small>{run.commit || text(language, "无提交引用", "No commit reference")}</small></span><span className="mono table-desktop-only">{run.commit || "—"}</span><span className="table-detail" data-label={text(language, "开始时间", "Started")}>{new Date(run.startedAt).toLocaleString(language === "zh" ? "zh-CN" : "en-US")}</span><span className="table-detail" data-label={text(language, "耗时", "Duration")}>{run.endedAt ? `${Math.max(1, Math.round((Date.parse(run.endedAt) - Date.parse(run.startedAt)) / 1000))}s` : (run.status === "running" ? text(language, "运行中", "Running") : text(language, "未结束", "Not finished"))}</span><span className="table-detail table-source" data-label={text(language, "来源", "Source")}>{run.kind === "recorded-demo" ? <SourceBadge source="recorded-demo" language={language} /> : <SourceBadge source={run.executionTarget === "local-codex" ? "local-runner" : "attested"} language={language} />}</span><span className="table-detail table-result" data-label={text(language, "结果", "Result")}><StatusBadge status={run.status} language={language} /></span><span className="table-arrow"><ArrowRight /></span></button>)}</div></section> : <EmptyState icon={History} title={text(language, "还没有运行记录", "No runs yet")} description={text(language, "批准计划并开始运行后，记录会保存在这里。", "Runs are recorded here after a plan is approved and started.")} actions={<button className="primary-button" onClick={() => navigate("plan")}>{text(language, "查看计划", "Open plan")}</button>} />}</div>;
}
